name: Benchmark

on:
    workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      # BENCH_ROOT: ${{github.workspace}}/MobileGL/MG_Benchmark
      BENCH_ROOT: ${{github.workspace}}

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 32

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Update glslang external sources
        working-directory: ${{env.BENCH_ROOT}}/3rdparty/glslang
        run: python update_glslang_sources.py

      - name: Install clang-20
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-20 clang++-20 lld-20 libc++-20-dev libc++abi-20-dev libvulkan-dev

      - name: Show installed toolchain
        run: |
          clang-20 --version
          clang++-20 --version
          ld.lld-20 --version || ld.lld --version || true
          dpkg -l 'libc++*' || true

      - name: Configure CMake
        working-directory: ${{env.BENCH_ROOT}}
        run: cmake -S . -B build-bench -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON -DBENCHMARK_ENABLE_TESTING=OFF -DMOBILEGL_BUILD_TEST=OFF -DMOBILEGL_BUILD_BENCHMARK=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        working-directory: ${{env.BENCH_ROOT}}/build-bench
        run: cmake --build .

      - name: Benchmark
        working-directory: ${{env.BENCH_ROOT}}/build-bench/MobileGL/MG_Benchmark
        run: ctest -V -C Release
