name: Build

on:
  push:           # 推送时自动触发
    branches:
      - main
      - master
      - dev
  pull_request:   # 有 PR 创建或更新时自动触发
    branches:
      - main
      - master
      - dev
  schedule:       # 每天凌晨 2 点自动触发，支持定时（可选）
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Update glslang external sources
        working-directory: ${{github.workspace}}/3rdparty/glslang
        run: python update_glslang_sources.py

      - name: Install clang-20
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-20 clang++-20 lld-20 libc++-20-dev libc++abi-20-dev libvulkan-dev

      - name: Show installed toolchain
        run: |
          clang-20 --version
          clang++-20 --version
          ld.lld-20 --version || ld.lld --version || true

      - name: Configure with CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build